server:
  http_port: 8081  # 监听的HTTP端口
  grpc_port: 50051  # 监听的gRPC端口
  environment: dev  # 环境名称，可选值：dev,  prod ,test(可选)
  
log:
  level: info # 日志级别，可选值：debug, info, warn, error, fatal, panic
  filename: ./logs/app.log
  maxsize: 100    # 每个日志文件的最大尺寸(MB)
  maxbackups: 3   # 保留的旧日志文件最大数量 
  maxage: 7       # 保留的旧日志文件最大天数
  compress: true  # 是否压缩旧日志文件
  console: true   # 是否同时输出到控制台

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 10

database:
  dsn: "root:pass123@tcp(192.168.110.21:3306)/newb?charset=utf8mb4&parseTime=True&loc=Local"
  log_level: "info"
  slow_threshold: 1s
  dry_run: false
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 30m
